a=input("enter message signal amplitude");
f=input("enter message signal frequency");
t=0:0.02:2;
x1=1;
x2=a*sin(2*pi*f*t);
y=x1*x2;
subplot(3,1,1);
stem(x1);
title('impluse signal');
xlabel('time');
ylabel('amplitude');
subplot(3,1,2);
plot(t,x2);
title('sine wave');
xlabel('time');
ylabel('amplitude');
subplot(3,1,3);
stem(t,y);
title('PAM ideal wave');
xlabel('time');
ylabel('amplitude');