clc;
fc=200;
fm=50;
fs=1000;
a=5;
t=1;
n=[0:1/fs:t];
n=n(1:end-1);
dutycycle=50;
s=square(2*pi*fc*n,dutycycle);
s(find(s<0))=0;
plot(s);
m=5*sin(2*pi*fm*n);
period_sam=length(n)/fc;
ind=1:period_sam:length(n);
on_samp=ceil(period_sam*dutycycle/100);
pam=zeros(1,length(n));
for i=1:length(ind)
pam(ind(i):ind(i)+on_samp)=m(ind(i));
end
subplot(3,1,1);
plot(n,s,'b');
grid on;
xlabel('time');
ylabel('amplitude');
title('square waveform');
ylim([-1,2]);
subplot(3,1,2);
plot(n,m,'g');
grid on;
xlabel('time');
ylabel('amplitude');
title('sine wave');
ylim([-10,10]);
subplot(3,1,3);
plot(n,pam,'r');
grid on;
xlabel('time');
ylabel('amplitude');
title('pam wave');
ylim([-10,10]);